name: meetup
description: A new Flutter project.

publish_to: 'none'

version: 2.3.0+6

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  basic_utils: ^4.2.2
  cached_network_image: ^3.2.1
  clipboard: ^0.1.3
  cool_alert: ^1.1.0
  dartx: ^1.1.0
  dio: ^4.0.6
  easy_onboard: ^1.0.3
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_messaging: ^11.2.13
  flag: ^5.0.1
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_local_notifications: ^9.4.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  google_mobile_ads: ^1.2.0
  google_nav_bar: ^5.0.6
  i18n_extension: ^5.0.0
  image_picker: ^0.8.5+3
  in_app_review: ^2.0.4
  jiffy: ^5.0.0
  jitsi_meet_wrapper: ^0.0.5
  line_icons: ^2.0.1
  localize_and_translate: ^4.1.1
  onboarding: ^3.1.0
  package_info_plus: ^1.4.2
  pin_code_fields: ^7.4.0
  provider: ^6.0.3
  pull_to_refresh: ^2.0.0
  random_string: ^2.3.1
  share_plus: ^4.0.7
  shared_preferences: ^2.0.15
  stacked: ^2.3.12
  translator: ^0.1.7
  url_launcher: ^6.1.3
  velocity_x: ^3.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.2.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  image: assets/images/app_icon.png
  color: "20063B"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/
    - assets/
